[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    { name = "Nobuyuki Sekimori", email = "43375309+juno-rmks@users.noreply.github.com" },
]
name = "Utsuho"
description = "A Python library for deterministic normalization of Japanese text variants."
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = ["Programming Language :: Python"]
dependencies = ["click>=8.1.7"]
dynamic = ["version"]

[project.urls]
"Source Code" = "https://github.com/juno-rmks/utsuho/"
"Issue Tracker" = "https://github.com/juno-rmks/utsuho/issues/"
"Documentation" = "https://utsuho.readthedocs.io/"

[project.optional-dependencies]
test = ["pytest", "coverage", "pytest-benchmark", "pytest-mock"]
docs = [
    "Sphinx==5.3.0",
    "sphinx-intl==2.1.0",
    "sphinx-rtd-theme==1.2.0",
    "myst-parser==1.0.0",
]
dev = ["build", "twine", "pylint", "black", "isort", "Utsuho[test,docs]"]

[tool.setuptools.dynamic]
version = { attr = "utsuho.__version__" }

[project.scripts]
utsuho = "utsuho.cli:cli"

[tool.pylint.format]
max-line-length = 88

[tool.pylint.messages_control]
disable = ["too-many-instance-attributes", "too-few-public-methods"]

[tool.black]
skip-string-normalization = true
extend-exclude = "docs/source/conf.py"

[tool.isort]
profile = "black"
skip_glob = ["docs/source/conf.py"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib", "--benchmark-skip"]
filterwarnings = ["error"]
testpaths = ["tests"]
markers = ["benchmark: performance benchmarks"]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
